### ISSUE TITLE
Comparison with capistrano-php-fpm

### ISSUE THREAD

**Issue by timkelty** [nexylan/capistrano-fpm#2]
These 2 gems seem really similar.

Would be great if you could highlight the differences, and why one might choose one over the other, and if this package was created with knowledge of https://github.com/glooby/capistrano-php-fpm

Thanks!

**Comment by Soullivaneuh** [comment]
Hi @timkelty,

I didn't know about this plugin. Ours was developed for internal and customer needs first of all.

They are indeed similar except `glooby/capistrano-php-fpm` give only reload and restart commands, we propose all of them: https://github.com/nexylan/capistrano-fpm#usage

But I don't know what you mean by highlighting the differences. What is missing on our usage documentation?

Regards.

**Comment by timkelty** [comment]
Thats it, I really just wanted to know if it was intentionally made as an alternative for any specific reason.

Thanks for the quick reply!
